---
title: "JSC370 Final Project"
author: "Karim Zakir"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.

```{r source, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library("tidyverse")
library("plotly")
source("process_COVID_data.R")
```

```{r plot1}
p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~naive_CFR,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Naive Case Fatality Rate (CFR) vs. population density",
                  yaxis = list(title = "Naive CFR"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~naive_CFR,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Naive Case Fatality Rate (CFR) vs. population density",
                  yaxis = list(title = "Naive CFR"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

p3_bar <- cv_states_today %>% 
  plot_ly(x = ~per100k, y = ~state, type = "bar", color = ~state, 
          hoverinfo = 'text', 
          text = ~paste( paste(state, ":", sep = ""), paste(" Cases per 100k: ", per100k, sep=""), paste(" Deathers per 100k: ", deathsper100k, sep=""), sep = "<br>")) %>% 
  layout(title = "Cumulative cases per 100k per state (as of March 23rd)", 
         xaxis = list(title = "Cases per 100k"),
         yaxis = list(title = "State"),
         hovermode = "compare")

p4_bar <- cv_states_today %>% 
  plot_ly(x = ~naive_CFR, y = ~state, type = "bar", color = ~state, 
          hoverinfo = 'text', 
          text = ~paste( paste(state, ":", sep = ""), paste(" Cases per 100k: ", per100k, sep=""), paste(" Deaths per 100k: ", deathsper100k, sep=""), sep = "<br>")) %>% 
  layout(title = "Naive Case Fatality Rate per state (as of March 23rd)", 
         xaxis = list(title = "Naive CFR"),
         yaxis = list(title = "State"),
         hovermode = "compare")

```



## Showcasing plots {.tabset}

### Figure 1

```{r}
p1_scatter
```

### Figure 2

```{r}
p2_scatter
```

### Figure 3

```{r}
p3_bar
```

### Figure 4

```{r}
p4_bar
```


{-}